[package]
name = "shogi"
version = "0.5.0"
authors = ["Takashi Nozawa <nozazon@gmail.com>"]
description = "A library providing various types and implementations for representing concepts and rules in Shogi."
keywords = ["shogi", "move", "usi", "sfen"]
categories = ["game-engines"]
repository = "https://github.com/nozaq/shogi-rs"
documentation = "http://nozaq.github.io/shogi-rs"
readme = "README.md"
license = "MIT"

[dependencies]
itertools = "0.5.9"

[badges]
travis-ci = { repository = "nozaq/shogi-rs" }
